bind-addr: 127.0.0.1:8080
auth: none
disable-telemetry: true
disable-update-check: true
disable-getting-started-override: true
disable-file-downloads: true
disable-file-uploads: true
app-name: "VSCode Local"